# Generated by Django 4.1 on 2022-11-16 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('no_enregistrement', models.IntegerField()),
                ('patient_first_name', models.CharField(max_length=100)),
                ('patient_last_name', models.CharField(max_length=100)),
                ('patient_birth_day', models.DateField()),
                ('patient_genre', models.CharField(max_length=50)),
                ('doctor_send_from', models.CharField(max_length=100)),
                ('date_prelevement', models.DateField()),
                ('exm_type', models.CharField(max_length=100)),
                ('tests_examen', models.CharField(max_length=200)),
                ('test_seen', models.CharField(max_length=50)),
                ('result_ready', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ExamenTestes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('exam_test', models.CharField(max_length=50)),
                ('exam_type', models.CharField(max_length=100)),
                ('exam_color', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InfPrileve',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Laboriste',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Resultat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_result', models.DateField()),
                ('result_tests', models.CharField(max_length=50)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labo.examen')),
                ('laboriste_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labo.laboriste')),
            ],
        ),
        migrations.AddField(
            model_name='examen',
            name='inf_prelevement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labo.infprileve'),
        ),
    ]
