# Generated by Django 4.1 on 2022-11-29 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examen',
            name='tests_examen',
        ),
        migrations.CreateModel(
            name='TestDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('resultat_test', models.CharField(max_length=100)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labo.examen')),
                ('examen_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labo.examentestes')),
            ],
        ),
    ]
